# Supported themes - https://pages.github.com/themes/
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Scientific Instrumentation]
description: [The Evergreen State College]