project:
  type: website
  title: "Scientific Instrumentation"
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "Instrumentation/*.qmd"
    - "MetaCategory/*.qmd"
  preview:
    browser: false
website:
  navbar:
    search: true
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "Meta-Categories" 
        menu:
          - text: "Data Loggers"
            href: "MetaCategory/DataLoggers.qmd"
          - text: "Imaging"
            href: "MetaCategory/Imaging.qmd"
          - text: "Microscopy"
            href: "MetaCategory/Microscopy.qmd"
          - text: "Spectroscopy"
            href: "MetaCategory/Spectroscopy.qmd"                      
          - text: "Other"
            href: "MetaCategory/Other.qmd"
      - text: "Instruments" 
        menu:
          - text: "Agilent ICP-MS 7850"
            href: "Instrumentation/Agilent-ICP-MS-7850.qmd"
          - text: "Instron 34SC-1"
            href: "Instrumentation/Instron-34SC-1.qmd"
          - text: "Molecular Devices SpectraMax iD3 Microplate Reader"
            href: "Instrumentation/Molecular-Devices-SpectraMax-iD3-Microplate-Reader.qmd"
      - text: "Logbooks"
        menu:
          - text: "Index"
            href: "Instrumentation/Logbooks.qmd"
          - text: "Disaster Recovery"
            href: "Instrumentation/Disaster_Recovery_Table.qmd"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/The-Evergreen-State-College/Scientific-Instrumentation
          - text: Submit ticket
            href: https://github.com/The-Evergreen-State-College/Scientific-Instrumentation/issues
execute:
  freeze: auto
  cache: true