project:
  type: website
  output-dir: docs
website:
  title: "Scientific-Instrumentation"
  navbar:
    left:
      - href: readme.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - solorized-light
      - brand
    css: styles.css
    toc: true



